import pdfplumber
import io
import re
from typing import cast
from app.utils.chunking import chunk_text
from app.rag.embeddings import embed_batch
from app.rag.vector_store import add_documents
from app.database import SessionLocal
from app.models.document import Document


def process_pdf(file_bytes: bytes, filename: str) -> int:

    text = ""

    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"

    if not text.strip():
        return 0

    text = re.sub(r'(.)\1+', r'\1', text)

    chunks = chunk_text(text)

    if not chunks:
        return 0

    db = SessionLocal()

    try:
        document = Document(
            name=filename,
            doc_type="internal",
            jurisdiction=None,
            version="1.0"
        )

        db.add(document)
        db.commit()
        db.refresh(document)

        # ✅ SAFE
        document_id: int = cast(int, document.id)

        if document_id is None:
            raise ValueError("Document ID not generated by database.")

        embeddings = embed_batch(chunks)

        add_documents(document_id, chunks, embeddings)

        return len(chunks)

    finally:
        db.close()